apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 76
      targetPort: 5022
      nodePort: 30083  # must be in range 30000–32767
